version: '3.0'

services: 
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: prod_pass
      POSTGRES_DB: prod_db
    ports:
      - 5432:5432
    volumes:
      - app-volume:/var/lib/postgresql/data
  db-test:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: test_db
    ports:
      - 5433:5432

volumes:
  app-volume:
